const categories = [
    {
        theme: "Sitcoms",
        answers: [
            "Friends",
            "Cheers",
            "Frasier",
            "How I Met Your Mother",
            "New Girl",
            "Brooklyn Nine-Nine",
            "30 Rock",
            "3rd Rock From the Sun",
            "Seinfeld",
            "Curb Your Enthusiasm",
            "Fresh Prince of Bel Air",
            "Family Matters",
            "Big Bang Theory",
            "Young Sheldon",
            "Trailer Park Boys",
            "Two and Half Men",
            "Everybody Loves Raymond",
            "King of Queens",
            "Full House",
            "The Office",
            "Parks and Rec",
            "The Good Place",
            "Community",
            "Arrested Development",
        ]
    },
    {
        theme: "Classic Rock Bands",
        answers: [
            "Beatles",
            "Rolling Stones",
            "Who",
            "Kinks",
            "Janis Joplin",
            "Jimi Hendrix",
            "Doors",
            "ABBA",
            "Elvis Pressley",
            "Lynard Skynard",
            "AC/DC",
            "Led Zeppelin",
            "Pink Floyd",
            "Black Sabbath",
            "Aerosmith",
            "Kiss",
            "David Bowie",
            "Velvet Underground",
            "Creedence Clearwater Revival",
            "Jefferson Airplane",
            "Earth, Wind, and Fire",
            "Bob Dylan",
            "Steve Miller Band",
            "Frank Zappa",
        ]
    },
    {
        theme: "Mammals",
        answers: [
            "Dog",
            "Cat",
            "Rabbit",
            "Cow",
            "Horse",
            "Goat",
            "Pig",
            "Llama",
            "Sheep",
            "Lion",
            "Tiger",
            "Bear",
            "Racoon",
            "Mouse",
            "Whale",
            "Deer",
            "Elephant",
            "Gorilla",
            "Giraffe",
            "Monkey",
            "Squirrel",
            "Groundhog",
            "Zebra",
            "Donkey",
        ]
    },
    {
        theme: "Home Game Consoles",
        answers: [
            "Playstation",
            "Playstation 2",
            "Playstation 3",
            "Playstation 4",
            "Playstation 5",
            "Nintendo",
            "Super Nintendo",
            "Nintendo 64",
            "GameCube",
            "Wii",
            "Wii U",
            "Switch",
            "Master System",
            "Genesis",
            "Saturn",
            "Dreamcast",
            "X-Box",
            "X-Box 360",
            "X-Box One",
            "X-Box Series X",
            "Atari 2600",
            "Jaguar",
            "Phillips CD-i",
            "ColecoVision",
        ]
    }
]

export default categories;

// {
//     theme: "",
//     answers: [
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//         "",
//     ]
// }